// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcdCWMVdcXi2_U4ZByfv7GiwK1YxsdQI',
    appId: '1:100321766900:web:63dde557b455f924abdda1',
    messagingSenderId: '100321766900',
    projectId: 'ci-cd-testing-8e5e1',
    authDomain: 'ci-cd-testing-8e5e1.firebaseapp.com',
    storageBucket: 'ci-cd-testing-8e5e1.appspot.com',
    measurementId: 'G-58WSTR52W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZim8PiVs6iegIEqbet7KNKBB06OWSEUY',
    appId: '1:100321766900:android:89ceba838ccddbe9abdda1',
    messagingSenderId: '100321766900',
    projectId: 'ci-cd-testing-8e5e1',
    storageBucket: 'ci-cd-testing-8e5e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmR-WdrK6hFcjA_p5Uu2W9QvguGAZJF2I',
    appId: '1:100321766900:ios:ac169e0b0be1eb59abdda1',
    messagingSenderId: '100321766900',
    projectId: 'ci-cd-testing-8e5e1',
    storageBucket: 'ci-cd-testing-8e5e1.appspot.com',
    iosClientId: '100321766900-pu81rl2s1uj8qiss0ibttqgm60rcujfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingCiCd',
  );
}
