name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build and Test
        run: flutter test

#      - name: Build apk
#        run: flutter build apk

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Firebase
        run: |
          firebase use default 

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting  # Adjust the options as needed
            

        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
